### ISSUE TITLE
BlockBot doesn't work

### ISSUE THREAD

**Issue by souljaboycrankdat** [sagirilover/AnimeSoftware#10]
BlockBot doesn't even block people who are running into you, and has very delayed movements when your ontop of someone's head. And yes, I updated offsets

**Comment by sagirilover** [comment]
i think the problem is your cpu performance

**Comment by souljaboycrankdat** [comment]
Should I run the game in windowed? I have a i5 and it runs games perfectly. I play the game on RealTime with -high in launch options.

**Comment by sagirilover** [comment]
the problem on user side.
