### ISSUE TITLE
Can you add some features like this ?

### ISSUE THREAD

**Issue by muratcansimsek** [sagirilover/AnimeSoftware#2]
-Fake VAC
-Rank Changer
-Fake case unboxing
-Fake vote (press f1 to kick cheater)
-Rank revealer
-glow key (hold / on,off)

maybe help you this link ; https://www.unknowncheats. me/forum/counterstrike-global-offensive/354169-fake-unboxing-vac-ban.html

**Comment by muratcansimsek** [comment]
HELLO

**Comment by nikk735** [comment]
lol you do it urself

**Comment by muratcansimsek** [comment]
nO

**Comment by InternalxHD** [comment]
Your not paying him to do this, do it yourself u lazy noob

**Comment by muratcansimsek** [comment]
> Your not paying him to do this, do it yourself u lazy noob

It's just a request why you act like a fool, most of you are tense and stupid.
