### ISSUE TITLE
Having troubles updating the offsets

### ISSUE THREAD

**Issue by DatSkyr3x** [sagirilover/AnimeSoftware#6]
Ok so I'm pretty retarded and I don't know which offsets I have to replace with what. I use the offsets thread on UC and it lists the names but they don't all match the ones in this cheat. Can someone tell me what all the oofsets I gotta change are called in the offsets.cs and what they represent on the UC thread?

**Comment by DatSkyr3x** [comment]
So i noticed that it says to update using hazedumper. i downloaded it, ran it and all the files are basically empty. what did i do wrong?

**Comment by sagirilover** [comment]
Go to [hazedumper](https://github.com/frk1/hazedumper) and paste to Offsets.cs from csgo.cs.
Or use hazedumper.exe with config.json and paste from generated files.
