### ISSUE TITLE
update broke cheat

### ISSUE THREAD

**Issue by PapaBill1234** [sagirilover/AnimeSoftware#8]
So I was able to use this no problem just by updating the offsets but for some reason something has changed and I am unable to use it even tho i updated to the latest offset. All features dont work even tho I can open a handle to the game normally but I think its somekind of offset that is hardcoded into the cheat or something else. Could you take a look at it or atleast point me into the right direction of where is should be to fix this issue

**Comment by sagirilover** [comment]
update offsets normally, everything works for me and my friends. I did not change anything except offsets. if you broke something, then just download a clean build and update offsets.

**Comment by sagirilover** [comment]
in uc thread, he said that he decided this by the reboot computer lol
