### ISSUE TITLE
Did not work

### ISSUE THREAD

**Issue by LDzik** [sagirilover/AnimeSoftware#9]
So i build this in a visual studio and i dont see the names of players on list, block bot dont work,  dorspammer and few more. Animated clantag and velocity clantag work. Please help. Im new at this so i can do something wrong. (Sorry for my bad English)

**Comment by sagirilover** [comment]
![chrome_O7mnWD6IZV](https://user-images.githubusercontent.com/32457153/79504525-b36e5680-803b-11ea-814b-738d448f312f.png)

**Comment by souljaboycrankdat** [comment]
> 
> 
> ![chrome_O7mnWD6IZV](https://user-images.githubusercontent.com/32457153/79504525-b36e5680-803b-11ea-814b-738d448f312f.png)

Didn't you update offsets to the latest?

**Comment by sagirilover** [comment]
no

**Comment by LDzik** [comment]
What are offsets (I'm new at this, so I can dont know this)

**Comment by sagirilover** [comment]
https://github.com/sagirilover/AnimeSoftware/issues/1
